// Warehouses are relevant in multiple areas (most importantly Territory) and cause cycles
import { BuildingMaterial, Inventory, ProductionGood, Weapon } from "../Goods";
import { StandardTile, toProductivity } from "./Tile";
import { TileChecker } from "./TileChecker";
import { Coordinate } from "../Coordinate";

export type WarehouseGoods =
  | BuildingMaterial
  | ProductionGood
  | Weapon
  | "Money";

export type Warehouse = StandardTile<
  "Warehouse",
  WarehouseGoods,
  "Nothing",
  "Money" | "Wood" | "Tool"
>;

/**
 * Proto tile companion object which breaks the create instance cycle
 */
export const Warehouse: Omit<Warehouse, "create"> = {
  tag: "Warehouse",
  consumes: {
    Tool: 100,
    Wood: 100,
    Marble: 100,
    Brick: 100,
    Bread: 100,
    Meat: 100,
    Stone: 100,
    Bells: 100,
    Engineer: 100,
    Alcohol: 100,
    Amber: 100,
    Beer: 100,
    Bees: 100,
    Book: 100,
    BronzeBar: 100,
    Ceramic: 100,
    Clay: 100,
    Cloth: 100,
    Clothes: 100,
    Coal: 100,
    Cocoa: 100,
    CopperBar: 100,
    CopperOre: 100,
    Cotton: 100,
    Finery: 100,
    Flour: 100,
    Flowers: 100,
    Food: 100,
    Fish: 100,
    GemStone: 100,
    GoldBar: 100,
    Wheat: 100,
    GunPowder: 100,
    Hemp: 100,
    Honey: 100,
    Hops: 100,
    Horse: 100,
    Indigo: 100,
    Ink: 100,
    Instrument: 100,
    IronBar: 100,
    IronOre: 100,
    Jewellery: 100,
    LampOil: 100,
    Leather: 100,
    Paper: 100,
    Pelt: 100,
    Perfume: 100,
    Pigment: 100,
    Porcelain: 100,
    Potato: 100,
    RawHide: 100,
    Rope: 100,
    Sails: 100,
    Salt: 100,
    Silk: 100,
    SilverBar: 100,
    SilverOre: 100,
    Slag: 100,
    Spices: 100,
    Spirit: 100,
    Sugar: 100,
    SugarCane: 100,
    TinBar: 100,
    Tobacco: 100,
    TobaccoLeaf: 100,
    WhaleTallow: 100,
    Wine: 100,
    Wool: 100,
    Pike: 100,
    Sword: 100,
    Armor: 100,
    Musket: 100,
    Cannon: 100,
    Mortar: 100,
    WarHorse: 100,
    Money: Number.MAX_SAFE_INTEGER,
  },
  produces: Inventory.NOTHING,
  costs: {
    Money: 1000,
    Wood: 40,
    Tool: 40,
  },
  initialState: {
    Tool: 20,
    Wood: 20,
    Marble: 0,
    Brick: 0,
    Bread: 0,
    Meat: 0,
    Stone: 0,
    Bells: 0,
    Engineer: 0,
    Alcohol: 0,
    Amber: 0,
    Beer: 0,
    Bees: 0,
    Book: 0,
    BronzeBar: 0,
    Ceramic: 0,
    Clay: 0,
    Cloth: 0,
    Clothes: 0,
    Coal: 0,
    Cocoa: 0,
    CopperBar: 0,
    CopperOre: 0,
    Cotton: 0,
    Finery: 0,
    Flour: 0,
    Flowers: 0,
    Food: 20,
    Fish: 0,
    GemStone: 0,
    GoldBar: 0,
    Wheat: 0,
    GunPowder: 0,
    Hemp: 0,
    Honey: 0,
    Hops: 0,
    Horse: 0,
    Indigo: 0,
    Ink: 0,
    Instrument: 0,
    IronBar: 0,
    IronOre: 0,
    Jewellery: 0,
    LampOil: 0,
    Leather: 0,
    Paper: 0,
    Pelt: 0,
    Perfume: 0,
    Pigment: 0,
    Porcelain: 0,
    Potato: 0,
    RawHide: 0,
    Rope: 0,
    Sails: 0,
    Salt: 0,
    Silk: 0,
    SilverBar: 0,
    SilverOre: 0,
    Slag: 0,
    Spices: 0,
    Spirit: 0,
    Sugar: 0,
    SugarCane: 0,
    TinBar: 0,
    Tobacco: 0,
    TobaccoLeaf: 0,
    WhaleTallow: 0,
    Wine: 0,
    Wool: 0,
    Pike: 0,
    Sword: 0,
    Armor: 0,
    Musket: 0,
    Cannon: 0,
    Mortar: 0,
    WarHorse: 0,
    Money: 1000,
  },
  formula: {
    Nothing: {},
  },

  allowed: TileChecker.create("Grass", "Forest"),

  influence: (coord): Coordinate[] => Coordinate.range(coord, 10),

  productivity: () => toProductivity(1),
  baseProductivity: () => toProductivity(1),
};
